CREATE TABLE weather_aqi (
	city_id SERIAL PRIMARY KEY,
	city_name varchar(50) NOT NULL,
	"Date" DATETIME NOT NULL,
	latitude REAL NOT NULL,
	longitude REAL NOT NULL,
	AQI INT NOT NULL,
	CO REAL NOT NULL,
	"NO" REAL NOT NULL,
	NO2 REAL NOT NULL,
	O3 REAL NOT NULL,
	SO2 REAL NOT NULL,
	PM2_5 REAL NOT NULL,
	PM10 REAL NOT NULL,
	NH3 REAL NOT NULL
);